version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      VK_TOKEN: ${VK_TOKEN}
    command: ["sh", "-c", "./main -telegram-token=${TELEGRAM_TOKEN} -vk-token=${VK_TOKEN}"]
